swagger: "2.0"
info:
  description: "Swagger API specification file for process flow diagram."
  version: "1.0.0"
  title: "Flow Diagram"
  termsOfService: "NA"
  contact:
    email: "rrmackay@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost"
basePath: "/api/v1"
schemes:
- "https"
- "http"
paths:
  /node:
    post:
      summary: "Add a new node to the database"
      description: ""
      operationId: "addNode"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "NodeModel object that needs to be added to the diagram"
        required: true
        schema:
          $ref: "#/definitions/Node"
      responses:
        405:
          description: "Invalid input"
      security:
      - nodediagram_auth:
        - "write:nodes"
        - "read:nodes"
    put:
      tags:
      - "Node"
      summary: "Update an existing Node"
      description: ""
      operationId: "updateNode"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Node object that needs to be added to the diagram"
        required: true
        schema:
          $ref: "#/definitions/Node"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "Node not found"
        405:
          description: "Validation exception"
      security:
      - nodediagram_auth:
        - "write:nodes"
        - "read:nodes"
    get:
      tags:
      - "Node"
      summary: "get all nodes"
      description: "Returns an array pf Nodes"
      operationId: "getNodes"
      produces:
      - "application/xml"
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Node"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Node not found"
      security:
      - api_key: []
  /node/{NodeId}:
    get:
      tags:
      - "Node"
      summary: "Find Node by ID"
      description: "Returns a single Node"
      operationId: "getNodeById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
      - name: "NodeId"
        in: "path"
        description: "ID of Node to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Node"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Node not found"
      security:
      - api_key: []
securityDefinitions:
  nodediagram_auth:
    type: "oauth2"
    authorizationUrl: "http://Nodediagram.swagger.io/oauth/dialog"
    flow: "implicit"
    scopes:
      write:nodes: "modify node in your account"
      read:nodes: "read your node"
  api_key:
    type: "apiKey"
    name: "api_key"
    in: "header"
definitions:
  Node:
    type: "object"
    properties:
      id:
        type: string
      offsetY: 
        type: number
      offsetX: 
        type: number
      content: 
          type: string
      shape_type: 
          type: string
      shape_name: 
          type: string 
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
